language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
  - travis_retry sudo apt-get install parallel
  - composer self-update

install:
  - composer install
  - composer update
